version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  iot-data-receiver:
    lang: java11
    handler: ./iot-data-receiver
    image: carrone/iot-data-receiver:latest
    environment:
      write_debug: true
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s
  iot-data-reducer:
    lang: java11
    handler: ./iot-data-reducer
    image: carrone/iot-data-reducer:latest
    environment:
      write_debug: true
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s

