apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-garbage-collector
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: url-caller-garbage-collector
            image: k3d-docker-io.localhost:5000/curl:latest
            command:
              - sh
              - -c
              - curl http://gateway.openfaas.svc.cluster.local:8080/function/session-offloading-manager?command=garbage-collector
          restartPolicy: OnFailure
