version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  session-offloading-manager:
    lang: java11
    handler: ./session-offloading-manager
    image: carrone/session-offloading-manager:latest

