version: 1.0
provider:
  name: openfaas
functions:
  session-offloading-manager:
    lang: java11
    handler: ./session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
  session-offloading-manager-update-session:
    lang: java11
    handler: ./session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
  session-offloading-manager-migrate-session:
    lang: java11
    handler: ./session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1

