version: 1.0
provider:
  name: openfaas
functions:
  cdn-download:
    lang: java17
    handler: ./cdn/cdn-download
    image: k3d-docker-io.localhost:5000/cdn-download:latest
  cdn-upload:
    lang: java17
    handler: ./cdn/cdn-upload
    image: k3d-docker-io.localhost:5000/cdn-upload:latest

  example:
    lang: java17
    handler: ./cron-function-example/example
    image: k3d-docker-io.localhost:5000/example:latest
    #this makes the function "cron"
    annotations:
      topic: cron-function
      schedule: "*/1 * * * *" #this is a 1 minutes timer
  #check here how to make other schedules: https://crontab.guru/#*/1_*_*_*_*

  empty-function:
    lang: java17
    handler: ./empty-function/empty-function
    image: k3d-docker-io.localhost:5000/empty-function:latest

  products-counter:
    lang: java17
    handler: ./shopping-carts/shopping-cart
    image: k3d-docker-io.localhost:5000/shopping-cart:latest
  shopping-cart:
    lang: java17
    handler: ./shopping-carts/shopping-cart
    image: k3d-docker-io.localhost:5000/shopping-cart:latest

  session-offloading-manager:
    lang: java17
    handler: ./openfaas-offloading-session/session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
  session-offloading-manager-update-session:
    lang: java17
    handler: ./openfaas-offloading-session/session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
  session-offloading-manager-migrate-session:
    lang: java17
    handler: ./openfaas-offloading-session/session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
  session-offloading-manager-garbage-collector:
    lang: java17
    handler: ./openfaas-offloading-session/session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest

  session-offloading-manager-trigger:
    lang: java17
    handler: ./openfaas-offloading-session/session-offloading-manager
    image: k3d-docker-io.localhost:5000/session-offloading-manager:latest
    annotations:
      topic: cron-trigger
      schedule: "*/1 * * * *" # 1 minute
