{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openfaas",
    "module": "entrypoint",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openfaas",
          "module": "model",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "entrypoint-2.1.0.jar",
          "url": "entrypoint-2.1.0.jar",
          "size": 5107,
          "sha512": "99ac8ceff69c6d695f1ddb242c91f51b9a03dab8d1695b1d865299ce1bb4f4702a16beb5f8af00242666308ae0123b37265ae495e67fa5dad3e5b03dbb2939e0",
          "sha256": "557fbd17e42f120b4d1e3650cbc78224fc6ba71686890c25908b0e77a141fc40",
          "sha1": "3c7dd511971e40a2640b51576759322170805934",
          "md5": "6d27e5e3d96f7d88d33d6ebf05f942c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-http-spi",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.eclipse.jetty",
          "module": "jetty-server",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.openfaas",
          "module": "model",
          "version": {
            "requires": "2.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "entrypoint-2.1.0.jar",
          "url": "entrypoint-2.1.0.jar",
          "size": 5107,
          "sha512": "99ac8ceff69c6d695f1ddb242c91f51b9a03dab8d1695b1d865299ce1bb4f4702a16beb5f8af00242666308ae0123b37265ae495e67fa5dad3e5b03dbb2939e0",
          "sha256": "557fbd17e42f120b4d1e3650cbc78224fc6ba71686890c25908b0e77a141fc40",
          "sha1": "3c7dd511971e40a2640b51576759322170805934",
          "md5": "6d27e5e3d96f7d88d33d6ebf05f942c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entrypoint-2.1.0-javadoc.jar",
          "url": "entrypoint-2.1.0-javadoc.jar",
          "size": 83412,
          "sha512": "2a87206eae85010b152808b852db5cf701a5d490d7c16e0e33c5b980d2b77af6a4b455a3c17ca4d3c479542a7126f2fa0cd841ca9ba8ebbf2f6f0c4038e6289e",
          "sha256": "ae7f8738fdf3c83126a6cd278741e88518de7e5420335188c5ca1f0b84c80cce",
          "sha1": "8b8e999ea59650415a551b292e1ffe0e3ffeaf32",
          "md5": "0e4f0ca2e0262df9f36a06862bfdd318"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entrypoint-2.1.0-sources.jar",
          "url": "entrypoint-2.1.0-sources.jar",
          "size": 2757,
          "sha512": "cfed7ab5d06425b7cc83375e4fee6a2a48625c6b586d474b4bb122238983a412a41b0b8885760057bc4c16c666ba5cc2308bc39b94281c7a00c12f8a82282d37",
          "sha256": "c92956c2842896a59cfbe1eefe1f4f99489039ea53df6a36f59aa481a9c55f52",
          "sha1": "b18f5fce1e865b4216a1866419e67f70ede0498c",
          "md5": "bcf77ad37e2b223379d70039f00172bc"
        }
      ]
    }
  ]
}
