version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  search-analytics-data-receivers:
    lang: java11
    handler: ./search-analytics-data-receivers
    image: carrone/search-analytics-data-receivers:latest
    environment:
      write_debug: true
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s
  search-analytics-store-data:
    lang: java11
    handler: ./search-analytics-store-data
    image: carrone/search-analytics-store-data:latest
    environment:
      write_debug: true
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s
  search-analytics-performer:
    lang: java11
    handler: ./search-analytics-performer
    image: carrone/search-analytics-performer:latest
    environment:
      write_debug: true
      write_timeout: 2m30s
      read_timeout: 2m
      exec_timeout: 2m
      handler_wait_duration: 1m30s
      healthcheck_interval: 5s

