version: 1.0
provider:
  name: openfaas
functions:
  products-counter:
    lang: java17
    handler: ./shopping-cart
    image: k3d-docker-io.localhost:5000/shopping-cart:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
  shopping-cart:
    lang: java17
    handler: ./shopping-cart
    image: k3d-docker-io.localhost:5000/shopping-cart:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 1
