version: 1.0
provider:
  name: openfaas
functions:
  example:
    lang: java17
    handler: ./example
    image: k3d-docker-io.localhost:5000/example:latest
    #this makes the function "cron"
    annotations:
      topic: cron-function
      schedule: "*/1 * * * *" #this is a 1 minutes timer
#check here how to make other schedules: https://crontab.guru/#*/1_*_*_*_*
