{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openfaas",
    "module": "EdgeDb",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.2.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "EdgeDb-2.0.0.jar",
          "url": "EdgeDb-2.0.0.jar",
          "size": 78921,
          "sha512": "282b2b3614391079c5725f17715c2043c78d9d8e7ce4f54fe4f458c742b3c83c67232b8e9b3e911e0ccc00de4c350cb345c0f313af42629f2984630625735f44",
          "sha256": "575d30f23bd3a9d6320ffb670d7bcb5bd68a2d234f27c277fe838bbc73680eed",
          "sha1": "0dc690cc4328071dbbc10269a5e652dc856627dd",
          "md5": "c4a62c60c1d81c38ef739c851abb024a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openfaas",
          "module": "model",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "joda-time",
          "module": "joda-time",
          "version": {
            "requires": "2.12.2"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.2.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "EdgeDb-2.0.0.jar",
          "url": "EdgeDb-2.0.0.jar",
          "size": 78921,
          "sha512": "282b2b3614391079c5725f17715c2043c78d9d8e7ce4f54fe4f458c742b3c83c67232b8e9b3e911e0ccc00de4c350cb345c0f313af42629f2984630625735f44",
          "sha256": "575d30f23bd3a9d6320ffb670d7bcb5bd68a2d234f27c277fe838bbc73680eed",
          "sha1": "0dc690cc4328071dbbc10269a5e652dc856627dd",
          "md5": "c4a62c60c1d81c38ef739c851abb024a"
        }
      ]
    }
  ]
}
