apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: k3d-docker-io.localhost:5000/proxy:latest  # Replace with your Docker image details
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
