apiVersion: k3d.io/v1alpha4
kind: Simple
registries:
  use:
    - k3d-docker-io.localhost:5000
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - http://k3d-docker-io.localhost:5000
options:
  k3d:
    disableLoadbalancer: true
