version: 1.0
provider:
  name: openfaas
functions:
  cdn-download:
    lang: java17
    handler: ./cdn-download
    image: k3d-docker-io.localhost:5000/cdn-download:latest
  cdn-upload:
    lang: java17
    handler: ./cdn-upload
    image: k3d-docker-io.localhost:5000/cdn-upload:latest

